language = "c"
include_guard = "_LONGPORTWHALE_H_"
documentation_style = "doxy"
cpp_compat = true

[export.rename]
"CHttpClient" = "lb_http_client_t"
"CHeader" = "lb_http_header_t"
"CHttpResult" = "lb_http_result_t"
"CLanguage" = "lb_language_t"
"CDecimal" = "lb_decimal_t"
"CAsyncCallback" = "lb_async_callback_t"
"CAsyncResult" = "lb_async_result_t"
"CError" = "lb_error_t"
"CConfig" = "lb_config_t"
"CSubscription" = "lb_subscription_t"
"CPushTrades" = "lb_push_trades_t"
"CDate" = "lb_date_t"
"CTime" = "lb_time_t"
"CDateTime" = "lb_datetime_t"
"CTradeContext" = "lb_trade_context_t"
"CTopicType" = "lb_topic_type_t"
"COrderSide" = "lb_order_side_t"
"COrderType" = "lb_order_type_t"
"COrderStatus" = "lb_order_status_t"
"COrderTag" = "lb_order_tag_t"
"CTriggerStatus" = "lb_trigger_status_t"
"COnOrderChangedCallback" = "lb_order_changed_callback_t"
"CPushOrderChanged" = "lb_push_order_changed_t"
"CFreeUserDataFunc" = "lb_free_userdata_func_t"


[export]
include = [
    "CSubscription",
]
