[tasks.java]
command = "cargo"
args = ["build", "-p", "longportwhale-java"]

[tasks.javah]
args = [
  "--release",
  "8",
  "-h",
  "c",
  "-cp",
  "libs/native-lib-loader-2.4.0.jar;libs/slf4j-api-1.7.30.jar;libs/gson-2.10.1.jar",
  "-sourcepath",
  "javasrc/src/main/java",
  "-d",
  "classes",
  "javasrc/src/main/java/com/longportwhale/SdkNative.java",
]
command = "javac"
cwd = "java"

[tasks.compile-java-test]
args = [
  "--release",
  "8",
  "-cp",
  "libs/native-lib-loader-2.4.0.jar;libs/slf4j-api-1.7.30.jar;libs/gson-2.10.1.jar",
  "-sourcepath",
  "javasrc/src/main/java",
  "-d",
  "classes",

  "javasrc/src/main/java/com/longportwhale/AsyncCallback.java",
  "javasrc/src/main/java/com/longportwhale/Config.java",
  "javasrc/src/main/java/com/longportwhale/ConfigBuilder.java",
  "javasrc/src/main/java/com/longportwhale/Language.java",
  "javasrc/src/main/java/com/longportwhale/Market.java",
  "javasrc/src/main/java/com/longportwhale/OpenApiException.java",
  "javasrc/src/main/java/com/longportwhale/SdkNative.java",
  "javasrc/src/main/java/com/longportwhale/AsyncCallback.java",
  "javasrc/src/main/java/com/longportwhale/HttpClient.java",
  "javasrc/src/main/java/com/longportwhale/trade/OrderChangedHandler.java",
  "javasrc/src/main/java/com/longportwhale/trade/OrderSide.java",
  "javasrc/src/main/java/com/longportwhale/trade/OrderStatus.java",
  "javasrc/src/main/java/com/longportwhale/trade/OrderTag.java",
  "javasrc/src/main/java/com/longportwhale/trade/OrderType.java",
  "javasrc/src/main/java/com/longportwhale/trade/PushOrderChanged.java",
  "javasrc/src/main/java/com/longportwhale/trade/TopicType.java",
  "javasrc/src/main/java/com/longportwhale/trade/TradeContext.java",
  "javasrc/src/main/java/com/longportwhale/trade/TriggerStatus.java",
  "test/Main.java",
]
command = "javac"
cwd = "java"

[tasks.test-java]
command = "java"
args = [
  "-Djava.library.path=target/debug",
  "-cp",
  "java/classes;java/libs/native-lib-loader-2.4.0.jar;java/libs/slf4j-api-1.7.30.jar;java/libs/gson-2.10.1.jar",
  "Main",
]
dependencies = ["java", "compile-java-test"]
