/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longportwhale_SdkNative */

#ifndef _Included_com_longportwhale_SdkNative
#define _Included_com_longportwhale_SdkNative
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    init
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_init(JNIEnv*, jclass);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newHttpClient
   * Signature:
   * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
   */
  JNIEXPORT jlong JNICALL
  Java_com_longportwhale_SdkNative_newHttpClient(JNIEnv*,
                                                 jclass,
                                                 jstring,
                                                 jstring,
                                                 jstring,
                                                 jstring);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newHttpClientFromEnv
   * Signature: ()J
   */
  JNIEXPORT jlong JNICALL
  Java_com_longportwhale_SdkNative_newHttpClientFromEnv(JNIEnv*, jclass);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    freeHttpClient
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_freeHttpClient(JNIEnv*, jclass, jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    httpClientRequest
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_httpClientRequest(JNIEnv*,
                                                     jclass,
                                                     jlong,
                                                     jstring,
                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newConfig
   * Signature:
   * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/longportwhale/Language;)J
   */
  JNIEXPORT jlong JNICALL Java_com_longportwhale_SdkNative_newConfig(JNIEnv*,
                                                                     jclass,
                                                                     jstring,
                                                                     jstring,
                                                                     jstring,
                                                                     jstring,
                                                                     jstring,
                                                                     jstring,
                                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newConfigFromEnv
   * Signature: ()J
   */
  JNIEXPORT jlong JNICALL
  Java_com_longportwhale_SdkNative_newConfigFromEnv(JNIEnv*, jclass);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    configRefreshAccessToken
   * Signature: (JLjava/time/OffsetDateTime;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_configRefreshAccessToken(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jobject,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    freeConfig
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_freeConfig(JNIEnv*,
                                                                     jclass,
                                                                     jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newQuoteContext
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_newQuoteContext(JNIEnv*,
                                                   jclass,
                                                   jlong,
                                                   jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    freeQuoteContext
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_freeQuoteContext(JNIEnv*, jclass, jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextGetMemberId
   * Signature: (J)J
   */
  JNIEXPORT jlong JNICALL
  Java_com_longportwhale_SdkNative_quoteContextGetMemberId(JNIEnv*,
                                                           jclass,
                                                           jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextGetQuoteLevel
   * Signature: (J)Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL
  Java_com_longportwhale_SdkNative_quoteContextGetQuoteLevel(JNIEnv*,
                                                             jclass,
                                                             jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSetOnQuote
   * Signature: (JLcom/longportwhale/quote/QuoteHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSetOnQuote(JNIEnv*,
                                                          jclass,
                                                          jlong,
                                                          jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSetOnDepth
   * Signature: (JLcom/longportwhale/quote/DepthHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSetOnDepth(JNIEnv*,
                                                          jclass,
                                                          jlong,
                                                          jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSetOnBrokers
   * Signature: (JLcom/longportwhale/quote/BrokersHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSetOnBrokers(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSetOnTrades
   * Signature: (JLcom/longportwhale/quote/TradesHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSetOnTrades(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSetOnCandlestick
   * Signature: (JLcom/longportwhale/quote/CandlestickHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSetOnCandlestick(JNIEnv*,
                                                                jclass,
                                                                jlong,
                                                                jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSubscribe
   * Signature: (J[Ljava/lang/String;IZLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSubscribe(JNIEnv*,
                                                         jclass,
                                                         jlong,
                                                         jobjectArray,
                                                         jint,
                                                         jboolean,
                                                         jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextUnsubscribe
   * Signature: (J[Ljava/lang/String;ILcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextUnsubscribe(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobjectArray,
                                                           jint,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSubscribeCandlesticks
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSubscribeCandlesticks(JNIEnv*,
                                                                     jclass,
                                                                     jlong,
                                                                     jstring,
                                                                     jobject,
                                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextUnsubscribeCandlesticks
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextUnsubscribeCandlesticks(JNIEnv*,
                                                                       jclass,
                                                                       jlong,
                                                                       jstring,
                                                                       jobject,
                                                                       jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextSubscriptions
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextSubscriptions(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextStaticInfo
   * Signature: (J[Ljava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextStaticInfo(JNIEnv*,
                                                          jclass,
                                                          jlong,
                                                          jobjectArray,
                                                          jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextQuote
   * Signature: (J[Ljava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextQuote(JNIEnv*,
                                                     jclass,
                                                     jlong,
                                                     jobjectArray,
                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextOptionQuote
   * Signature: (J[Ljava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextOptionQuote(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobjectArray,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextWarrantQuote
   * Signature: (J[Ljava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextWarrantQuote(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jobjectArray,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextDepth
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextDepth(JNIEnv*,
                                                     jclass,
                                                     jlong,
                                                     jstring,
                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextBrokers
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextBrokers(JNIEnv*,
                                                       jclass,
                                                       jlong,
                                                       jstring,
                                                       jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextParticipants
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextParticipants(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextTrades
   * Signature: (JLjava/lang/String;ILcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextTrades(JNIEnv*,
                                                      jclass,
                                                      jlong,
                                                      jstring,
                                                      jint,
                                                      jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextIntraday
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextIntraday(JNIEnv*,
                                                        jclass,
                                                        jlong,
                                                        jstring,
                                                        jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextCandlesticks
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;ILcom/longportwhale/quote/AdjustType;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextCandlesticks(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jstring,
                                                            jobject,
                                                            jint,
                                                            jobject,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextHistoryCandlesticksByOffset
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;Lcom/longportwhale/quote/AdjustType;ZLjava/time/LocalDateTime;ILcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextHistoryCandlesticksByOffset(
    JNIEnv*,
    jclass,
    jlong,
    jstring,
    jobject,
    jobject,
    jboolean,
    jobject,
    jint,
    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextHistoryCandlesticksByDate
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;Lcom/longportwhale/quote/AdjustType;Ljava/time/LocalDate;Ljava/time/LocalDate;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextHistoryCandlesticksByDate(
    JNIEnv*,
    jclass,
    jlong,
    jstring,
    jobject,
    jobject,
    jobject,
    jobject,
    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextOptionChainExpiryDateList
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextOptionChainExpiryDateList(
    JNIEnv*,
    jclass,
    jlong,
    jstring,
    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextOptionChainInfoByDate
   * Signature:
   * (JLjava/lang/String;Ljava/time/LocalDate;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextOptionChainInfoByDate(JNIEnv*,
                                                                     jclass,
                                                                     jlong,
                                                                     jstring,
                                                                     jobject,
                                                                     jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextWarrantIssuers
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextWarrantIssuers(JNIEnv*,
                                                              jclass,
                                                              jlong,
                                                              jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextWarrantList
   * Signature:
   * (JLcom/longportwhale/quote/QueryWarrantOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextWarrantList(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobject,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextTradingSession
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextTradingSession(JNIEnv*,
                                                              jclass,
                                                              jlong,
                                                              jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextTradingDays
   * Signature:
   * (JLcom/longportwhale/Market;Ljava/time/LocalDate;Ljava/time/LocalDate;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextTradingDays(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobject,
                                                           jobject,
                                                           jobject,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextCapitalFlow
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextCapitalFlow(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jstring,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextCapitalDistribution
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextCapitalDistribution(JNIEnv*,
                                                                   jclass,
                                                                   jlong,
                                                                   jstring,
                                                                   jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextCalcIndexes
   * Signature:
   * (J[Ljava/lang/String;[Lcom/longportwhale/quote/CalcIndex;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextCalcIndexes(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobjectArray,
                                                           jobjectArray,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextWatchlist
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextWatchlist(JNIEnv*,
                                                         jclass,
                                                         jlong,
                                                         jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextCreateWatchlistGroup
   * Signature:
   * (JLcom/longportwhale/quote/CreateWatchlistGroup;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextCreateWatchlistGroup(JNIEnv*,
                                                                    jclass,
                                                                    jlong,
                                                                    jobject,
                                                                    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextDeleteWatchlistGroup
   * Signature:
   * (JLcom/longportwhale/quote/DeleteWatchlistGroup;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextDeleteWatchlistGroup(JNIEnv*,
                                                                    jclass,
                                                                    jlong,
                                                                    jobject,
                                                                    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextUpdateWatchlistGroup
   * Signature:
   * (JLcom/longportwhale/quote/UpdateWatchlistGroup;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextUpdateWatchlistGroup(JNIEnv*,
                                                                    jclass,
                                                                    jlong,
                                                                    jobject,
                                                                    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextRealtimeQuote
   * Signature: (J[Ljava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextRealtimeQuote(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jobjectArray,
                                                             jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextRealtimeDepth
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextRealtimeDepth(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jstring,
                                                             jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextRealtimeBrokers
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextRealtimeBrokers(JNIEnv*,
                                                               jclass,
                                                               jlong,
                                                               jstring,
                                                               jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextRealtimeTrades
   * Signature: (JLjava/lang/String;ILcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextRealtimeTrades(JNIEnv*,
                                                              jclass,
                                                              jlong,
                                                              jstring,
                                                              jint,
                                                              jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    quoteContextRealtimeCandlesticks
   * Signature:
   * (JLjava/lang/String;Lcom/longportwhale/quote/Period;ILcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_quoteContextRealtimeCandlesticks(JNIEnv*,
                                                                    jclass,
                                                                    jlong,
                                                                    jstring,
                                                                    jobject,
                                                                    jint,
                                                                    jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    newTradeContext
   * Signature: (JLcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_newTradeContext(JNIEnv*,
                                                   jclass,
                                                   jlong,
                                                   jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    freeTradeContext
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_freeTradeContext(JNIEnv*, jclass, jlong);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextSetOnOrderChanged
   * Signature: (JLcom/longportwhale/trade/OrderChangedHandler;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextSetOnOrderChanged(JNIEnv*,
                                                                 jclass,
                                                                 jlong,
                                                                 jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextSubscribe
   * Signature: (J[Lcom/longportwhale/trade/TopicType;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextSubscribe(JNIEnv*,
                                                         jclass,
                                                         jlong,
                                                         jobjectArray,
                                                         jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextUnsubscribe
   * Signature: (J[Lcom/longportwhale/trade/TopicType;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextUnsubscribe(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobjectArray,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextHistoryExecutions
   * Signature:
   * (JLcom/longportwhale/trade/GetHistoryExecutionsOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextHistoryExecutions(JNIEnv*,
                                                                 jclass,
                                                                 jlong,
                                                                 jobject,
                                                                 jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextTodayExecutions
   * Signature:
   * (JLcom/longportwhale/trade/GetTodayExecutionsOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextTodayExecutions(JNIEnv*,
                                                               jclass,
                                                               jlong,
                                                               jobject,
                                                               jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextHistoryOrders
   * Signature:
   * (JLcom/longportwhale/trade/GetHistoryOrdersOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextHistoryOrders(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jobject,
                                                             jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextTodayOrders
   * Signature:
   * (JLcom/longportwhale/trade/GetTodayOrdersOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextTodayOrders(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobject,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextReplaceOrder
   * Signature:
   * (JLcom/longportwhale/trade/ReplaceOrderOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextReplaceOrder(JNIEnv*,
                                                            jclass,
                                                            jlong,
                                                            jobject,
                                                            jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextSubmitOrder
   * Signature:
   * (JLcom/longportwhale/trade/SubmitOrderOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextSubmitOrder(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jobject,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextCancelOrder
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextCancelOrder(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jstring,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextAccountBalance
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextAccountBalance(JNIEnv*,
                                                              jclass,
                                                              jlong,
                                                              jstring,
                                                              jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextCashFlow
   * Signature:
   * (JLcom/longportwhale/trade/GetCashFlowOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextCashFlow(JNIEnv*,
                                                        jclass,
                                                        jlong,
                                                        jobject,
                                                        jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextFundPositions
   * Signature:
   * (JLcom/longportwhale/trade/GetFundPositionsOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextFundPositions(JNIEnv*,
                                                             jclass,
                                                             jlong,
                                                             jobject,
                                                             jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextStockPositions
   * Signature:
   * (JLcom/longportwhale/trade/GetStockPositionsOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextStockPositions(JNIEnv*,
                                                              jclass,
                                                              jlong,
                                                              jobject,
                                                              jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextMarginRatio
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextMarginRatio(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jstring,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextOrderDetail
   * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextOrderDetail(JNIEnv*,
                                                           jclass,
                                                           jlong,
                                                           jstring,
                                                           jobject);

  /*
   * Class:     com_longportwhale_SdkNative
   * Method:    tradeContextEstimateMaxPurchaseQuantity
   * Signature:
   * (JLcom/longportwhale/trade/EstimateMaxPurchaseQuantityOptions;Lcom/longportwhale/AsyncCallback;)V
   */
  JNIEXPORT void JNICALL
  Java_com_longportwhale_SdkNative_tradeContextEstimateMaxPurchaseQuantity(
    JNIEnv*,
    jclass,
    jlong,
    jobject,
    jobject);

#ifdef __cplusplus
}
#endif
#endif
