/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longportwhale_SdkNative */

#ifndef _Included_com_longportwhale_SdkNative
#define _Included_com_longportwhale_SdkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longportwhale_SdkNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    newHttpClient
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longportwhale_SdkNative_newHttpClient
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    newHttpClientFromEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_longportwhale_SdkNative_newHttpClientFromEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    freeHttpClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_freeHttpClient
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    httpClientRequest
 * Signature: (JLjava/lang/String;Lcom/longportwhale/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_httpClientRequest
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    newConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/longportwhale/Language;)J
 */
JNIEXPORT jlong JNICALL Java_com_longportwhale_SdkNative_newConfig
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    newConfigFromEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_longportwhale_SdkNative_newConfigFromEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    configRefreshAccessToken
 * Signature: (JLjava/time/OffsetDateTime;Lcom/longportwhale/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_configRefreshAccessToken
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    freeConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_freeConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    newTradeContext
 * Signature: (JLcom/longportwhale/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_newTradeContext
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    freeTradeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_freeTradeContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    tradeContextSetOnOrderChanged
 * Signature: (JLcom/longportwhale/trade/OrderChangedHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_tradeContextSetOnOrderChanged
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    tradeContextSubscribe
 * Signature: (J[Lcom/longportwhale/trade/TopicType;Lcom/longportwhale/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_tradeContextSubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longportwhale_SdkNative
 * Method:    tradeContextUnsubscribe
 * Signature: (J[Lcom/longportwhale/trade/TopicType;Lcom/longportwhale/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longportwhale_SdkNative_tradeContextUnsubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
